listener {
    timeout = 240                            # in seconds.
    on-timeout = notify-send "Estas ahi?" # command to run when timeout has passed.
    on-resume = notify-send "Porfin volviste."  # command to run when activity is detected after timeout has fired.
}